change log type to json
1024pix/pix-360 pull request #114
Opened 2023-01-31 11:01 UTC by yoandl

## :egg: Problème
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._

## :bowl_with_spoon: Proposition
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._

## :milk_glass: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :butter: Pour tester
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._

2023-01-31 11:02 UTC, octo-topi approved these changes

2023-02-01 12:38 UTC, mickaelalibert requested changes
Sans le retour à la ligne les logs ne seront pas correctement remontés

2023-02-01 12:38 UTC, mickaelalibert commented on config/application.rb
> +    }.to_json
```suggestion
    }.to_json + $/ 
```
Sans ça, tous les logs sont envoyés sur la même ligne, ce qui va poser des problèmes de parsing

2023-02-01 12:38 UTC, mickaelalibert commented on config/application.rb
> +      type: severity,
```suggestion
      level: severity,
```
cf la [documentation Datadog](https://docs.datadoghq.com/fr/logs/log_configuration/pipelines/?tab=status#attribut-status), le status du log est récupéré par défaut dans une clé `status` ou `level`, autant rester dans les normes de ce qu'il se fait

2023-02-01 13:10 UTC, merged